"""Standard application answer preparation (docs/07C-2, docs/17 Phase 3).

Resolves the standard answer set deterministically from the Candidate
Knowledge Base with per-answer source attribution. Narrative answers are
generated by the provider from approved reusable answers. Anything that
cannot be resolved is reported explicitly as unresolved — never guessed.
"""

from __future__ import annotations

from pydantic import BaseModel, Field

from job_platform.candidate.context import build_candidate_context
from job_platform.candidate.models import CandidateBundle
from job_platform.jobs.models import Job
from job_platform.providers.base import ReasoningProvider
from job_platform.providers.tasks import NarrativeAnswerRequest
from job_platform.shared.errors import ProviderError
from job_platform.shared.logging import get_logger

logger = get_logger("preparation.answers")


class PreparedAnswer(BaseModel):
    answer_id: str
    question_family: str
    canonical_question: str
    answer: str
    source: str
    confidence: int = Field(ge=0, le=100)
    factual: bool = True
    approved: bool = True


class UnresolvedQuestion(BaseModel):
    question_family: str
    reason: str
    required_for_readiness: bool = False
    requires_user_input: bool = True


class PreparedAnswerSet(BaseModel):
    answers: list[PreparedAnswer] = Field(default_factory=list)
    unresolved: list[UnresolvedQuestion] = Field(default_factory=list)

    def answer_for(self, family: str) -> PreparedAnswer | None:
        for answer in self.answers:
            if answer.question_family == family:
                return answer
        return None


def _yes_no(value: bool) -> str:
    return "Yes" if value else "No"


def _document_line_lookup(bundle: CandidateBundle, doc: str, keywords: tuple[str, ...]) -> str:
    """Find the first line in a profile document mentioning any keyword."""
    for line in bundle.documents.get(doc, "").splitlines():
        lowered = line.lower()
        if any(keyword in lowered for keyword in keywords) and ":" in line:
            return line.split(":", 1)[1].strip()
    return ""


def resolve_standard_answers(bundle: CandidateBundle) -> PreparedAnswerSet:
    """Deterministic resolution of the standard factual answer set."""
    result = PreparedAnswerSet()
    personal = bundle.profile.personal
    employment = bundle.profile.employment
    education = bundle.profile.education
    auth = bundle.profile.work_authorization

    def add(family: str, question: str, value: str, source: str) -> None:
        result.answers.append(
            PreparedAnswer(
                answer_id=family.replace(".", "_"),
                question_family=family,
                canonical_question=question,
                answer=value,
                source=source,
                confidence=100,
            )
        )

    def unresolved(family: str, reason: str, required: bool) -> None:
        result.unresolved.append(
            UnresolvedQuestion(
                question_family=family, reason=reason, required_for_readiness=required
            )
        )

    personal_fields = [
        ("personal.first_name", "First name", personal.first_name, True),
        ("personal.last_name", "Last name", personal.last_name, True),
        ("personal.email", "Email address", personal.email, True),
        ("personal.phone", "Phone number", personal.phone, True),
        ("personal.address", "Street address", personal.address, False),
        ("personal.city", "City", personal.city, False),
        ("personal.state", "State or province", personal.state, False),
        ("personal.country", "Country", personal.country, False),
        ("personal.postal_code", "Postal code", personal.postal_code, False),
    ]
    for family, question, value, required in personal_fields:
        field = family.split(".", 1)[1]
        if value:
            add(family, question, str(value), f"candidate.json:personal.{field}")
        elif required:
            unresolved(family, f"candidate.json is missing personal.{field}.", True)

    if auth.authorized_to_work is not None:
        add(
            "work_authorization.authorized_now",
            "Are you legally authorized to work in the job's country?",
            _yes_no(auth.authorized_to_work),
            "candidate.json:work_authorization.authorized_to_work",
        )
    else:
        unresolved(
            "work_authorization.authorized_now",
            "work_authorization.authorized_to_work is not set in candidate.json.",
            True,
        )
    if auth.requires_sponsorship is not None:
        add(
            "work_authorization.sponsorship_now",
            "Will you now or in the future require sponsorship for employment?",
            _yes_no(auth.requires_sponsorship),
            "candidate.json:work_authorization.requires_sponsorship",
        )
    else:
        unresolved(
            "work_authorization.sponsorship_now",
            "work_authorization.requires_sponsorship is not set in candidate.json.",
            True,
        )
    if auth.visa_status:
        add(
            "work_authorization.visa_status",
            "What is your current visa status?",
            auth.visa_status,
            "candidate.json:work_authorization.visa_status",
        )

    if employment.current_company:
        add(
            "employment.current_company",
            "Current employer",
            employment.current_company,
            "candidate.json:employment.current_company",
        )
    if employment.current_title:
        add(
            "employment.current_title",
            "Current job title",
            employment.current_title,
            "candidate.json:employment.current_title",
        )
    if employment.years_of_experience:
        add(
            "employment.years_of_experience",
            "Years of professional experience",
            str(employment.years_of_experience),
            "candidate.json:employment.years_of_experience",
        )

    if education.highest_degree:
        add(
            "education.highest_degree",
            "Highest degree obtained",
            education.highest_degree,
            "candidate.json:education.highest_degree",
        )
    if education.university:
        add(
            "education.institution",
            "School or university",
            education.university,
            "candidate.json:education.university",
        )

    # Preference-based answers parsed from profile documents.
    lookups = [
        ("preferences.salary_expectation", "Salary expectation", ("salary",), False),
        ("employment.notice_period", "Notice period", ("notice",), False),
        ("preferences.start_date", "Earliest start date", ("start date",), False),
        ("preferences.relocation", "Willingness to relocate", ("relocat",), False),
        ("preferences.travel", "Maximum travel percentage", ("travel",), False),
    ]
    for family, question, keywords, required in lookups:
        for doc in ("preferences", "answers", "notes"):
            value = _document_line_lookup(bundle, doc, keywords)
            if value:
                add(family, question, value, f"{doc}.md")
                break
        else:
            unresolved(
                family,
                f"No stored value for {question.lower()} in the candidate files.",
                required,
            )

    return result


NARRATIVE_FAMILIES = [
    ("narrative.why_company", "Why do you want to work here?"),
    ("narrative.tell_us_about_yourself", "Tell us about yourself."),
]


def edit_prepared_answer(
    store,
    manifest,
    answer_id: str,
    new_answer: str,
    question: str = "",
    save_for_reuse: bool = False,
    candidate_profile_dir=None,
) -> PreparedAnswer:
    """Apply a user edit to one prepared answer (docs/17 Phase 4 acceptance).

    The edited answer becomes user-approved with source ``user_edit``. If it
    resolves an unresolved question, that question is removed. With
    ``save_for_reuse`` the answer is also appended to the user's answers.md —
    the explicit request is the user approval the CKB rules require.
    """
    import json as _json

    from job_platform.shared.errors import StorageError

    answers_doc = _json.loads(
        store.read_artifact(manifest.package_id, "answers/prepared_answers.json")
    )
    answers = answers_doc.get("answers", [])
    target = next((a for a in answers if a["answer_id"] == answer_id), None)
    if target is not None:
        target["answer"] = new_answer
        target["source"] = "user_edit"
        target["approved"] = True
        target["confidence"] = 100
        edited = PreparedAnswer.model_validate(target)
    else:
        # An edit may resolve a previously-unresolved question. Match by the
        # normalized id (families use dots, answer ids use underscores).
        try:
            unresolved_doc = _json.loads(
                store.read_artifact(
                    manifest.package_id, "answers/unresolved_questions.json"
                )
            )
        except StorageError:
            unresolved_doc = {"questions": []}
        questions = unresolved_doc.get("questions", [])
        normalized = answer_id.replace(".", "_")
        match = next(
            (
                q
                for q in questions
                if q.get("question_family", "").replace(".", "_") == normalized
            ),
            None,
        )
        if match is None:
            raise StorageError(
                f"No prepared or unresolved answer '{answer_id}' exists in this package.",
                details={"package_id": manifest.package_id, "answer_id": answer_id},
            )
        family = match["question_family"]
        edited = PreparedAnswer(
            answer_id=family.replace(".", "_"),
            question_family=family,
            canonical_question=question or family,
            answer=new_answer,
            source="user_edit",
            confidence=100,
            factual=True,
            approved=True,
        )
        answers.append(edited.model_dump())
        unresolved_doc["questions"] = [q for q in questions if q is not match]
        store.write_artifact(
            manifest,
            "answers/unresolved_questions.json",
            _json.dumps(unresolved_doc, indent=2),
        )

    store.write_artifact(
        manifest, "answers/prepared_answers.json", _json.dumps(answers_doc, indent=2)
    )
    store.save_manifest(manifest)

    if save_for_reuse and candidate_profile_dir is not None:
        answers_md = candidate_profile_dir / "answers.md"
        existing = answers_md.read_text(encoding="utf-8") if answers_md.exists() else ""
        entry = f"\n\n## {edited.canonical_question}\n\n{new_answer}\n"
        answers_md.write_text(existing.rstrip() + entry, encoding="utf-8")
        logger.info("Saved edited answer '%s' to answers.md for reuse", edited.question_family)
    return edited


async def prepare_answers(
    provider: ReasoningProvider,
    job: Job,
    bundle: CandidateBundle,
    include_narratives: bool = True,
) -> PreparedAnswerSet:
    result = resolve_standard_answers(bundle)
    if not include_narratives:
        return result

    context = build_candidate_context(
        bundle,
        resume=bundle.resumes[0] if bundle.resumes else None,
        include_answers=True,
    )
    for family, question in NARRATIVE_FAMILIES:
        try:
            narrative = await provider.generate_application_answer(
                NarrativeAnswerRequest(
                    job=job,
                    canonical_question=question,
                    question_family=family,
                    candidate_context=context,
                )
            )
        except ProviderError as exc:
            logger.warning("Narrative generation failed for %s: %s", family, exc.message)
            result.unresolved.append(
                UnresolvedQuestion(
                    question_family=family,
                    reason=f"Narrative generation failed: {exc.message}",
                    required_for_readiness=False,
                )
            )
            continue
        result.answers.append(
            PreparedAnswer(
                answer_id=family.replace(".", "_"),
                question_family=family,
                canonical_question=question,
                answer=narrative.answer,
                source="provider:narrative_from_approved_answers",
                confidence=int(narrative.confidence * 100),
                factual=False,
                approved=False,  # narrative answers require user review
            )
        )
    return result
